### App Request

GET http://localhost:3000/

### All Message Request

GET http://localhost:3000/messages

### Selected Message Request

GET http://localhost:3000/messages/14528

### post user

POST http://localhost:3000/users
Content-Type: application/json

{
"userName": "bidule457",
"userPassword" : "guçihiojdap74496hzdpo_ayhè-çà_èuà",
"userId" : "427guvjhker"
}